### ISSUE TITLE
[1.14.4] Multiplayer Randomness

### ISSUE THREAD

**Issue by Axebeard2025** [ModdingForBlockheads/PrettyBeaches#13]
Pretty Beaches seems to work perfectly in Single-Player Survival mode.

In Multi-Player Survival, the effect of Pretty Beaches is random.  Sometimes it fills in water, other times not.  I have not been able to see any pattern to it.

Observed in:

Minecraft 1.14.4
Mods:
- Forge 1.14.4-28.2.1
- Pretty Beaches 1.14.4-3.0.7

**Comment by BlayTheNinth** [comment]
Closing since 1.14 is no longer supported
